[global]
developmentMode = false

[theme]
base                     = "light"
primaryColor             = "#1B7A47"
backgroundColor          = "#F0F4F8"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#111827"
font                     = "sans serif"

[server]
headless = true
